version: '3'
services:
  app:
    tty: true
    container_name: bank-app
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODES=${XDEBUG_MODES}
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
      - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT}
      - IDE_KEY=${IDE_KEY}
    depends_on:
      - db
    volumes:
      - ./:/var/www
  db:
    image: mysql:8
    user: 1000:1000
    tty: true
    container_name: bank-mysql
    ports:
      - "5001:3306"
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pass --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
  web:
    image: nginx:1.19
    tty: true
    container_name: bank-web
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
    ports:
      - "5000:80"
